blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/UjjwalSaini07/Bharat-Bhakti-Yatra/discussions
    about: Please ask and answer questions here before creating an issue.

  - name: 🌐 Author Website
    url: https://ujjwalsaini.dev
    about: Learn more about the project author (UjjwalS).

  - name: 📧 Security Contact
    url: mailto:ujjwalsaini0007+bharatbhaktiyatra@gmail.com
    about: Report critical vulnerabilities securely via email.
