name: '🌸 Top Contributors Recognition - Bharat-Bhakti-Yatra'

on:
  schedule:
    - cron: '0 9 * * 1' # Every Monday at 9 AM UTC
  workflow_dispatch:

jobs:
  leaderboard:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Top Contributors and Post Discussion
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Fetch contributors
            const contributors = await github.rest.repos.listContributors({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 5
            });

            if (contributors.data.length === 0) {
              console.log("No contributors found this week.");
              return;
            }

            // Prepare leaderboard
            const topContributors = contributors.data.map((c, index) => {
              let medal = "";
              if (index === 0) medal = "🥇";
              else if (index === 1) medal = "🥈";
              else if (index === 2) medal = "🥉";
              else medal = "🌟";

              return `${medal} @${c.login} — **${c.contributions} contributions**`;
            }).join("\n");

            // Build appreciation message
            const body = `
🌸 **Bharat-Bhakti-Yatra: Top Contributors of the Week** 🌸

Let's celebrate our amazing contributors who help make this spiritual journey of unity and devotion shine! 🙏

${topContributors}

💖 Your dedication strengthens the project and inspires the community.  

✨ **Keep contributing and spreading positivity!** Every effort counts in this sacred journey.  

_New contributors are always welcome! Explore issues labeled \`good first issue\` or \`help wanted\` to get started._ 🌺
`;

            // Find a valid discussion category (e.g., "Announcements")
            const categories = await github.rest.discussions.listCategories({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            const category = categories.data.find(c => c.name === "Announcements") || categories.data[0];

            if (!category) {
              console.log("⚠️ No discussion categories found. Please enable Discussions in your repo.");
              return;
            }

            // Create discussion instead of issue
            await github.rest.discussions.createDiscussion({
              owner: context.repo.owner,
              repo: context.repo.repo,
              category_id: category.id,
              title: "🏆 Top Contributors of the Week",
              body
            });

            console.log("✅ Top contributors recognition discussion created successfully.");
