name: "🌸 Welcome New Contributors - Bharat-Bhakti-Yatra"

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Post Welcome Message
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Assign GitHub username to JS variable
            const actor = context.actor;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const issue_number = context.issue.number;

            // Multiline message inside JS backticks
            const message = `
🌸 **Namaste @${actor}!**
Welcome to **Bharat-Bhakti-Yatra**. Thank you for opening a new issue or pull request and joining this divine journey of unity and devotion.  
🙏 **Your contribution matters:** Each issue helps us create a harmonious spiritual experience that connects hearts and souls across India’s diverse communities—Hindu, Muslim, Sikh, Jain, and more.  
🔹 Our team will review your submission and respond promptly. Please provide any additional context to help us improve this sacred journey.  
🌺 **Tip:** Label your issue clearly to guide us in addressing it efficiently.  
Let’s walk this path of oneness together! ✨
`;

            // Post comment using GitHub API
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body: message
            });

      - name: Add Welcome Label
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const issue_number = context.issue.number;

            // Fetch existing labels
            const { data: issue } = await github.rest.issues.get({
              owner,
              repo,
              issue_number
            });

            const labels = issue.labels.map(label => label.name);
            if (!labels.includes('welcome')) {
              await github.rest.issues.addLabels({
                owner,
                repo,
                issue_number,
                labels: ['welcome']
              });
              console.log(`🏷️ Added 'welcome' label to #${issue_number}`);
            }
